[project]
name = "fastaudio"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "mypy>=1.17.0",
    "pydantic-settings>=2.10.1",
    "ruff>=0.12.7",
    "uvicorn>=0.35.0",
]
