services:
  fastaudio_database_local:
    container_name: fastaudio_database_local
    image: postgres:17.5-alpine
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data

  fastaudio_app_local:
    container_name: fastaudio_app_local
    build:
      context: ../../
      dockerfile: deploy/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    command: >-
      sh -c "
      uv run uvicorn app.main:app --no-server-header --proxy-headers --workers=1 --host=${API_HOST} --port=${API_PORT} --lifespan on
      "
